### ISSUE TITLE
CI does not work for cross repo PRs

### ISSUE THREAD

**Issue by tomaszmichalak** [Knotx/knotx-aggregator#25]
During the clone phase the repository from where the change is requested should be cloned from fork.

**Comment by malaskowski** [comment]
It looks that `ORGANIZATION=$(cut -d'/' -f1 <<<$(Build.Repository.Name))` is not what we expected to be. In the following cross-repo PR: https://github.com/Knotx/knotx-stack/pull/94 this env returns `Knotx` while we expected it to return `gradleupdate`.
